### ISSUE TITLE
A few policy questions

### ISSUE THREAD

**Issue by gabesullice** [IcecaveStudios/repr#4]
Hi there! You've probably already [seen my other post](https://github.com/IcecaveStudios/parity/issues/15). Sorry if this feels like spamming :)

The Drupal project is considering adding a library that will add this library as one of our dev dependencies and so we're performing a standard stability review :)

I'm curious if you have any official policies documented somewhere WRT to:

- Security releases
  - For example, does more than one version receive security fixes, or only the current version?
- Release windows/cadence
  - For example, do they happen as necessary on any given day, or on a set schedule after a certain passage of time (e.g. once a month)?
- Backwards compatibility guarantees
  - I see the project uses semver, so I assume the major version promises not to break BC. However, is there any guarantee that a version will be supported for some period of time (an LTS version, for example)?

PS. I totally understand that these questions might be a little over the top if this project is a one-person shop, for the most part ;) Due diligence and whatnot.

**Comment by jmalloc** [comment]
Please see IcecaveStudios/parity#15.
